image: node:6.9.4

pipelines:
  default:
    - step:
        max-time: 5  #minutes
        caches:
          - node
        script:
          #load test database
          - apt-get update
          - apt-get install -y postgresql  #only need this to get psql
          - PGPASSWORD=test psql -h 127.0.0.1 -U vipfy_test_user -d test_database -f  vipfy_test_dump.sql
          
          #install dependencies
          - npm install
          - npm install lodash #TODO: fix package.json so we don't need this line
          
          #set config
          - echo -e "PORT=4001\nDB_NAME=vipfy_test_database\nDB_PORT=5432\nDB_USER=vipfy_test_user\nDB_PW=test\nENVIRONMENT=testing" > .env.test
          
          #run tests
          - npm run test app.spec.js
          - npm run test company.spec.js
          - npm run test message.spec.js
          - npm run test review.spec.js
          - npm run test user.spec.js
        services: 
          - postgres
          
definitions: 
  services: 
    postgres: 
      image: postgres 
      environment: 
        POSTGRES_DB: 'test_database' 
        POSTGRES_USER: 'vipfy_test_user'
        POSTGRES_PASSWORD: 'test'
