image: node:6.9.4

pipelines:
  default:
    - step:
        name: Run Unit Tests
        max-time: 5  #minutes
        caches:
          - node
        script:
          #load test database
          - apt-get update
          - apt-get install -y time postgresql  #only need postgresql to get psql
          - PGPASSWORD=test psql -h 127.0.0.1 -U vipfy_test_user -d test_database -f  vipfy_test_dump.sql
          
          #install dependencies
          - npm install
          - npm install lodash #TODO: fix package.json so we don't need this line
          
          #set config
          - echo -e "PORT=4001\nDB_NAME=vipfy_test_database\nDB_PORT=5432\nDB_USER=vipfy_test_user\nDB_PW=test\nDB_IP=127.0.0.1\nENVIRONMENT=testing" > .env.test
          
          #run tests
          - npm run test app.spec.js
          - npm run test auth.spec.js
          - npm run test message.spec.js
          - npm run test review.spec.js
          - npm run test user.spec.js
        services: 
          - postgres
  branches:
    development:
      - step:
          name: Run Unit Tests
          max-time: 5  #minutes
          caches:
            - node
          script:
            #load test database
            - apt-get update
            - apt-get install -y time postgresql  #only need postgresql to get psql
            - PGPASSWORD=test psql -h 127.0.0.1 -U vipfy_test_user -d test_database -f  vipfy_test_dump.sql
            
            #install dependencies
            - npm install
            - npm install lodash #TODO: fix package.json so we don't need this line
            
            #set config
            - echo -e "PORT=4001\nDB_NAME=vipfy_test_database\nDB_PORT=5432\nDB_USER=vipfy_test_user\nDB_PW=test\nDB_IP=127.0.0.1\nENVIRONMENT=testing" > .env.test
            
            #run tests
            - npm run test app.spec.js
            - npm run test auth.spec.js
            - npm run test message.spec.js
            - npm run test review.spec.js
            - npm run test user.spec.js
          services: 
            - postgres
      - step:
          name: Deploy to dev.vipfy.com
          image: keymetrics/pm2:latest-stretch
          deployment: test
          script:
            - echo "bitbucket.org,104.192.143.1 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==" >> ~/.ssh/known_hosts
            - ssh-keyscan -H dev.vipfy.com  >> ~/.ssh/known_hosts
            - pm2 deploy ecosystem.config.js dev update
definitions: 
  services: 
    postgres: 
      image: postgres 
      environment: 
        POSTGRES_DB: 'test_database' 
        POSTGRES_USER: 'vipfy_test_user'
        POSTGRES_PASSWORD: 'test'
