export const types = `
  type Website {
    website: String!
    tag: String
    verified: Boolean!
    autogenerated: Boolean!
    description: String
    priority: Int
    unitid: Unit
   }

   type Email {
     unitid: Unit!
     email: String!
     verified: Boolean!
     autogenerated: Boolean!
     description: String
     priority: Int
     tag: String
   }

  type Phone {
    number: String!
    verified: Boolean!
    autogenerated: Boolean!
    description: String
    priority: Int
    tag: String
    unitid: Unit!
  }

  type Address {
    id: Int!
    country: String!
    address: JSON
    description: String
    priority: Int
    tag: String
    unitid: Unit!
  }

  input AddressInput {
    street: String
    city: String
    state: String
    zip: String
  }
`;

export const queries = `
  fetchAddresses: [Address]!
`;

export const mutations = `
  # Without the id parameter, a new address will be generated. Otherwise it will be updated.
  updateAddress(id: Int, country: String, address: AddressInput, description: String, priority: Int): Response!
  #updateContactData(email: String):
`;
