export default (sequelize, { TEXT, BOOLEAN, INTEGER }) => {
  const DepartmentEmail = sequelize.define("department_all_emails_view", {
    email: { type: TEXT, allowNull: false },
    verified: BOOLEAN,
    autogenerated: BOOLEAN,
    description: TEXT,
    priority: INTEGER,
    tag: {
      type: TEXT,
      set(val) {
        this.setDataValue("tag", val.toLowerCase());
      }
    }
  });

  DepartmentEmail.associate = ({ Unit }) => {
    DepartmentEmail.belongsTo(Unit, { foreignKey: "departmentid" });
    DepartmentEmail.belongsTo(Unit, { foreignKey: "emailownerid" });
  };

  DepartmentEmail.removeAttribute("id");

  return DepartmentEmail;
};
