export default (sequelize, { TEXT, BOOLEAN, INTEGER, ARRAY }) => {
  const Email = sequelize.define("email_data", {
    email: { type: TEXT, allowNull: false, unique: true },
    verified: { type: BOOLEAN, defaultValue: false },
    autogenerated: { type: BOOLEAN, defaultValue: false },
    description: TEXT,
    priority: INTEGER,
    tags: {
      type: ARRAY(TEXT),
      set(values) {
        const normalizedValues = values.map(value => value.toLowerCase());
        this.setDataValue("tags", normalizedValues);
      }
    }
  });

  Email.associate = ({ Unit }) => Email.belongsTo(Unit, { foreignKey: "unitid" });

  Email.removeAttribute("id");

  return Email;
};
