export default (sequelize, { TEXT, BOOLEAN, INTEGER }) => {
  const Email = sequelize.define("email_data", {
    email: { type: TEXT, allowNull: false, unique: true },
    verified: { type: BOOLEAN, defaultValue: false },
    autogenerated: { type: BOOLEAN, defaultValue: false },
    description: TEXT,
    priority: INTEGER,
    tag: {
      type: TEXT,
      set(val) {
        this.setDataValue("tag", val.toLowerCase());
      }
    }
  });

  Email.associate = ({ Unit }) => Email.belongsTo(Unit, { foreignKey: "unitid" });

  Email.removeAttribute("id");

  return Email;
};
