export default (sequelize, { BOOLEAN, TEXT, INTEGER }) => {
  const Phone = sequelize.define("phone_data", {
    verified: { type: BOOLEAN, defaulValue: false },
    autogenerated: BOOLEAN,
    description: TEXT,
    priority: INTEGER,
    tag: TEXT
  });

  Phone.associate = ({ Unit }) => {
    Phone.belongsTo(Unit, { foreignKey: "unitid" });
  };

  return Phone;
};
