export default (sequelize, { BOOLEAN, TEXT, INTEGER, ARRAY }) => {
  const Phone = sequelize.define("phone_data", {
    number: { type: TEXT, allowNull: false },
    verified: { type: BOOLEAN, defaulValue: false },
    autogenerated: { type: BOOLEAN, defaultValue: false },
    description: TEXT,
    priority: INTEGER,
    tags: {
      type: ARRAY(TEXT),
      set(val) {
        this.setDataValue("tags", val.toLowerCase());
      }
    }
  });

  Phone.associate = ({ Unit }) => {
    Phone.belongsTo(Unit, { foreignKey: "unitid" });
  };

  Phone.removeAttribute("id");

  return Phone;
};
