export default (sequelize, { BOOLEAN, TEXT, INTEGER }) => {
  const Phone = sequelize.define("phone_data", {
    number: { type: TEXT, allowNull: false },
    verified: { type: BOOLEAN, defaulValue: false },
    autogenerated: { type: BOOLEAN, defaultValue: false },
    description: TEXT,
    priority: INTEGER,
    tag: TEXT
  });

  Phone.associate = ({ Unit }) => {
    Phone.belongsTo(Unit, { foreignKey: "unitid" });
  };

  Phone.removeAttribute("id");

  return Phone;
};
