export default (sequelize, { DATE, NOW, BOOLEAN }) => {
  const ReviewHelpful = sequelize.define(
    "reviewhelpful",
    {
      helpfuldate: {
        type: DATE,
        defaultValue: NOW
      },
      balance: BOOLEAN
    },
    {
      freezeTableName: true
    }
  );

  ReviewHelpful.associate = models => {
    ReviewHelpful.belongsTo(models.User, { foreignKey: "userid" });
    ReviewHelpful.belongsTo(models.Review, { foreignKey: "reviewid" });
  };

  //Remove autogenerated primary key
  ReviewHelpful.removeAttribute("id");

  return ReviewHelpful;
};
