export default (sequelize, { STRING, BOOLEAN }) => {
  const Speak = sequelize.define("speak", {
    language: {
      type: STRING,
      defaultValue: "English",
      allowNull: false
    },
    preferred: {
      type: BOOLEAN,
      defaultValue: false
    }
  });

  Speak.associate = models => {
    Speak.belongsTo(models.User, { foreignKey: "userid" });
  };

  // Remove the primary key which was autogenerated by sequelize
  Speak.removeAttribute("id");

  return Speak;
};
