export default (sequelize, { INTEGER }) => {
  const UserRight = sequelize.define("userright", {
    userright: {
      type: INTEGER,
      allowNull: false
    }
  });

  UserRight.associate = models => {
    UserRight.belongsTo(models.User, { foreignKey: "userid" });
    UserRight.belongsTo(models.Company, { foreignKey: "companyid" });
    UserRight.belongsTo(models.Department, { foreignKey: "departmentid" });
  };

  //Remove autogenerated primary key
  UserRight.removeAttribute("id");

  return UserRight;
};
