export default (sequelize, { STRING, INTEGER, DECIMAL, DATEONLY }) => {
  const UserBill = sequelize.define("userbill", {
    date: DATEONLY,
    billpos: INTEGER,
    textpos: STRING,
    price: DECIMAL(11, 2),
    currency: {
      type: STRING(3),
      validate: {
        len: [1, 3]
      }
    },
    orgcurrency: {
      type: STRING(3),
      validate: {
        len: [1, 3]
      }
    },
    exchangerate: DECIMAL(20, 10)
  });

  UserBill.associate = models => {
    UserBill.belongsTo(models.User, { foreignKey: "userid" });
    UserBill.belongsTo(models.Plan, { foreignKey: "planid" });
  };

  //Remove the primary key which was autogenerated by sequelize
  UserBill.removeAttribute("id");

  return UserBill;
};
