export default (sequelize, { TEXT, BOOLEAN, INTEGER }) => {
  const Website = sequelize.define("website_data", {
    website: {
      type: TEXT,
      primaryKey: true
    },
    tag: TEXT,
    verified: {
      type: BOOLEAN,
      defaulValue: false
    },
    autogenerated: BOOLEAN,
    description: TEXT,
    priority: INTEGER
  });

  Website.associate = ({ Unit }) => {
    Website.belongsTo(Unit, { foreignKey: "unitid" });
  };
  // Remove the autogenerated primary key
  Website.removeAttribute("id");

  return Website;
};
