export default (sequelize, { TEXT, BOOLEAN, INTEGER, ARRAY }) => {
  const Website = sequelize.define("website_data", {
    website: TEXT,
    tags: {
      type: ARRAY(TEXT),
      set(val) {
        this.setDataValue("tags", val.toLowerCase());
      }
    },
    verified: {
      type: BOOLEAN,
      defaulValue: false
    },
    autogenerated: { type: BOOLEAN, defaultValue: false },
    description: TEXT,
    priority: INTEGER
  });

  Website.associate = ({ Unit }) => {
    Website.belongsTo(Unit, { foreignKey: "unitid" });
  };
  // Remove the autogenerated primary key
  Website.removeAttribute("id");

  return Website;
};
