import { decode } from "jsonwebtoken";
import geoip from "geoip-country";
import { googleMapsClient } from "../../services/gcloud";
import { requiresRights, requiresAuth } from "../../helpers/permissions";
import { NormalError } from "../../errors";

export default {
  fetchAddresses: requiresRights(["view-addresses"]).createResolver(
    async (parent, { forCompany, tag }, { models, token }) => {
      try {
        let {
          // eslint-disable-next-line
          user: { unitid, company }
        } = decode(token);

        if (forCompany) {
          unitid = company;
        }

        const addresses = await models.Address.findAll({
          where: { unitid },
          order: [["priority", "ASC"]],
          tags: [tag]
        });

        return addresses;
      } catch (err) {
        throw new NormalError({ message: err.message, internalData: { err } });
      }
    }
  ),

  fetchEmails: requiresRights(["view-emails"]).createResolver(
    async (parent, { forCompany, tag }, { models, token }) => {
      try {
        const {
          user: { unitid, company }
        } = decode(token);

        const where = { autogenerated: false };

        if (forCompany) {
          where.departmentid = company;
        } else {
          where.emailownerid = unitid;
        }

        const emails = await models.DepartmentEmail.findAll({
          where,
          order: [["priority", "DESC"]],
          tags: [tag]
        });

        return emails;
      } catch (err) {
        throw new NormalError({ message: err.message, internalData: { err } });
      }
    }
  ),

  fetchPhones: requiresRights(["view-phones"]).createResolver(
    async (parent, { forCompany }, { models, token }) => {
      try {
        let {
          // eslint-disable-next-line
          user: { unitid, company }
        } = decode(token);

        if (forCompany) {
          unitid = company;
        }

        const phones = await models.Phone.findAll({
          where: { unitid },
          order: [["priority", "ASC"]]
        });

        return phones;
      } catch (err) {
        throw new NormalError({ message: err.message, internalData: { err } });
      }
    }
  ),

  searchAddressByCompanyName: requiresAuth.createResolver(
    async (parent, args, { models, token, ip }) => {
      try {
        const {
          user: { company }
        } = decode(token);

        const { name } = await models.Department.findOne({
          where: { unitid: company },
          raw: true
        });
        console.log("IP: ", ip);
        const config = { input: name };
        const geo = geoip.lookup(ip);
        console.log("GEO: ", geo);
        if (geo && geo.range) {
          config.location = {
            latitude: geo.range[0],
            longitude: geo.range[1]
          };
        }

        if (geo && geo.country) {
          config.language = geo.country;
        }

        const res = await googleMapsClient
          .placesQueryAutoComplete(config)
          .asPromise();

        return res.json.predictions;
      } catch (err) {
        throw new NormalError({ message: err.message, internalData: { err } });
      }
    }
  )
};
