export default (sequelize, { STRING, DATE }) => {
  const Employee = sequelize.define("employee", {
    begindate: DATE,
    enddate: DATE,
    position: STRING
  });

  Employee.associate = models => {
    Employee.belongsTo(models.Company, { foreignKey: "companyid" });
    Employee.belongsTo(models.Department, { foreignKey: "departmentid" });
    Employee.belongsTo(models.User, { foreignKey: "userid" });
  };

  //Remove the primary key which was autogenerated by sequelize
  Employee.removeAttribute("id");

  return Employee;
};
