export default (sequelize, { TEXT, INTEGER, DATE }) => {
  const Review = sequelize.define("review", {
    reviewdate: {
      type: DATE,
      allowNull: false
    },
    stars: {
      type: INTEGER
    },
    reviewtext: TEXT
  });

  Review.associate = models => {
    Review.belongsTo(models.User, { foreignKey: "userid" });
    Review.belongsTo(models.App, { foreignKey: "appid" });
  };

  //Remove the primary key which was autogenerated by sequelize
  Review.removeAttribute("id");

  return Review;
};
